import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'thermal-label',
  description: 'TypeScript drivers and transports for thermal label printers.',
  cleanUrls: true,

  // VitePress emits dist/sitemap.xml at build with one entry per page.
  sitemap: { hostname: 'https://thermal-label.github.io' },

  head: [
    ['link', { rel: 'sitemap', type: 'application/xml', href: '/sitemap.xml' }],
  ],

  // Per-driver content lands under docs/<repo>/ via scripts/pull-driver-docs.mjs.
  // - localhostLinks: dev-time references to local servers
  // - ./LICENSE in typedoc-generated api/README.md files: that LICENSE lives
  //   in the source repo, not in the docs site
  // - ./{core,node,web,cli}/dist/README inside <driver>/api/index.md: typedoc
  //   package-landing links that VitePress + cleanUrls mishandles even though
  //   README.md exists at the resolved path on disk
  ignoreDeadLinks: [
    'localhostLinks',
    /^\.\/LICENSE$/,
    /^\.\/(core|node|web|cli)\/dist\/README$/,
  ],

  // Exclude include-only fragments from routing.
  // _status-fragment.md is generated by scripts/build-hardware-page.mjs and
  // pulled into docs/<driver>/hardware.md via VitePress's @include directive.
  srcExclude: ['**/_*.md'],

  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/guide/introduction' },
      {
        text: 'Packages',
        items: [
          { text: 'contracts', link: '/contracts/' },
          { text: 'transport', link: '/transport/' },
          { text: 'brother-ql', link: '/brother-ql/' },
          { text: 'labelmanager', link: '/labelmanager/' },
          { text: 'labelwriter', link: '/labelwriter/' },
          { text: 'cli', link: '/cli/' },
        ],
      },
      { text: 'Hardware', link: '/hardware/' },
      { text: 'Demo', link: '/demo/' },
      { text: 'Related orgs', link: '/related-orgs' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Architecture', link: '/guide/architecture' },
            { text: 'Connecting your printer', link: '/guide/connecting-your-printer' },
            { text: 'Drivers', link: '/guide/drivers' },
            { text: 'CLI', link: '/guide/cli' },
            { text: 'Integrating', link: '/guide/integrating' },
            { text: 'Adding a driver', link: '/guide/adding-a-driver' },
          ],
        },
      ],

      '/contracts/': [
        {
          text: '@thermal-label/contracts',
          items: [
            { text: 'Overview', link: '/contracts/' },
          ],
        },
      ],

      '/transport/': [
        {
          text: '@thermal-label/transport',
          items: [
            { text: 'Overview', link: '/transport/' },
          ],
        },
      ],

      '/brother-ql/': [
        {
          text: '@thermal-label/brother-ql-*',
          items: [
            { text: 'Overview', link: '/brother-ql/' },
            { text: 'Getting started', link: '/brother-ql/getting-started' },
            { text: 'Core', link: '/brother-ql/core' },
            { text: 'Node', link: '/brother-ql/node' },
            { text: 'Web (WebUSB)', link: '/brother-ql/web' },
            { text: 'Hardware', link: '/brother-ql/hardware' },
            { text: 'Verification checklist', link: '/brother-ql/verification-checklist' },
            { text: 'Media', link: '/brother-ql/media' },
            { text: 'Troubleshooting', link: '/brother-ql/troubleshooting' },
            { text: 'Live demo', link: '/demo/brother-ql' },
          ],
        },
        {
          text: 'Wire protocols',
          items: [
            { text: 'Overview', link: '/brother-ql/protocol/' },
            { text: 'QL raster', link: '/brother-ql/protocol/ql' },
            { text: 'PT raster', link: '/brother-ql/protocol/pt' },
          ],
        },
        {
          text: 'API reference',
          collapsed: true,
          items: [{ text: 'TypeDoc index', link: '/brother-ql/api/' }],
        },
      ],

      '/labelmanager/': [
        {
          text: '@thermal-label/labelmanager-*',
          items: [
            { text: 'Overview', link: '/labelmanager/' },
            { text: 'Getting started', link: '/labelmanager/getting-started' },
            { text: 'Core', link: '/labelmanager/core' },
            { text: 'Node', link: '/labelmanager/node' },
            { text: 'Web', link: '/labelmanager/web' },
            { text: 'Hardware', link: '/labelmanager/hardware' },
            { text: 'Verification checklist', link: '/labelmanager/verification-checklist' },
            { text: 'Live demo', link: '/demo/labelmanager' },
          ],
        },
        {
          text: 'Wire protocols',
          items: [{ text: 'D1 tape', link: '/labelmanager/protocol' }],
        },
        {
          text: 'API reference',
          collapsed: true,
          items: [{ text: 'TypeDoc index', link: '/labelmanager/api/' }],
        },
      ],

      '/labelwriter/': [
        {
          text: '@thermal-label/labelwriter-*',
          items: [
            { text: 'Overview', link: '/labelwriter/' },
            { text: 'Getting started', link: '/labelwriter/getting-started' },
            { text: 'Core', link: '/labelwriter/core' },
            { text: 'Node', link: '/labelwriter/node' },
            { text: 'Web (WebUSB)', link: '/labelwriter/web' },
            { text: 'Hardware', link: '/labelwriter/hardware' },
            { text: 'Verification checklist', link: '/labelwriter/verification-checklist' },
            { text: 'Live demo', link: '/demo/labelwriter' },
          ],
        },
        {
          text: 'Wire protocols',
          items: [
            { text: 'Overview', link: '/labelwriter/protocol/' },
            { text: 'LW 450 raster', link: '/labelwriter/protocol/lw-450' },
            { text: 'LW 550 raster', link: '/labelwriter/protocol/lw-550' },
            { text: 'Duo tape', link: '/labelwriter/protocol/duo-tape' },
          ],
        },
        {
          text: 'API reference',
          collapsed: true,
          items: [{ text: 'TypeDoc index', link: '/labelwriter/api/' }],
        },
      ],

      '/cli/': [
        {
          text: 'thermal-label-cli',
          items: [
            { text: 'Overview', link: '/cli/' },
          ],
        },
      ],

      '/demo/': [
        {
          text: 'Live demos',
          items: [
            { text: 'Pick a printer family', link: '/demo/' },
            { text: 'Brother QL', link: '/demo/brother-ql' },
            { text: 'DYMO LabelManager', link: '/demo/labelmanager' },
            { text: 'DYMO LabelWriter', link: '/demo/labelwriter' },
          ],
        },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/thermal-label' }],

    // Per-section "Edit this page" routing. Most page paths under
    // docs/<repo>/ are pulled from sibling driver repos by
    // scripts/pull-driver-docs.mjs, so an edit on those needs to land
    // in the upstream repo, not this docs site. Generated landings
    // (hardware index, per-driver overview, api/index) point at the
    // build script that produces them. Per-device hardware pages set
    // `editLink: false` in their own frontmatter and ship a custom
    // "Edit device data" link straight to `data/devices/<KEY>.json5`,
    // so they never reach this function.
    editLink: {
      pattern: ({ filePath }) => {
        const ORG = 'thermal-label';
        const SITE_REPO = 'thermal-label.github.io';
        const PULLED = ['contracts', 'transport', 'brother-ql', 'labelmanager', 'labelwriter', 'cli'];

        if (filePath === 'hardware/index.md') {
          return `https://github.com/${ORG}/${SITE_REPO}/edit/main/scripts/build-hardware-page.mjs`;
        }

        const generatedLanding = filePath.match(/^([^/]+)\/(?:index\.md|api\/index\.md)$/);
        if (generatedLanding && PULLED.includes(generatedLanding[1])) {
          return `https://github.com/${ORG}/${SITE_REPO}/edit/main/scripts/build-hardware-page.mjs`;
        }

        const pulled = PULLED.find(r => filePath.startsWith(r + '/'));
        if (pulled) {
          const inner = filePath.slice(pulled.length + 1);
          return `https://github.com/${ORG}/${pulled}/edit/main/docs/${inner}`;
        }

        return `https://github.com/${ORG}/${SITE_REPO}/edit/main/docs/${filePath}`;
      },
      text: 'Edit this page on GitHub',
    },

    footer: {
      message:
        'MIT licensed projects. Not affiliated with printer manufacturers. <a href="https://github.com/thermal-label/thermal-label.github.io/issues/new?labels=docs&title=Docs+error%3A+" rel="noopener">Report a docs error</a> · <a href="https://github.com/sponsors/mannes" rel="noopener noreferrer">Sponsor on GitHub</a>',
      copyright: 'Copyright © thermal-label',
    },
    search: { provider: 'local' },
  },
});
